local_cpu: False
max_local_cpu_size: 5
max_local_disk_size: 0

enable_nixl: True
enable_xpyd: True
nixl_role: "sender"
nixl_proxy_host: "localhost"
nixl_proxy_port: 7500
nixl_buffer_size: 3774873600 # If you change model, it may raise issue that buffer size is not a multiple of a certain value. Please make sure to update this value.
nixl_buffer_device: "cuda"
nixl_backends: [UCX]