local_cpu: False
max_local_cpu_size: 0

enable_nixl: True
enable_xpyd: True
nixl_role: "receiver"
nixl_peer_host: "localhost"
nixl_peer_init_port: 7300
nixl_peer_alloc_port: 7400
nixl_buffer_size: 3774873600 # If you change model, it may raise issue that buffer size is not a multiple of a certain value. Please make sure to update this value.
nixl_buffer_device: "cuda"
nixl_backends: [UCX]