workload:
  type: long-doc-qa
  num_docs:             8
  doc_len:              20000
  out_len:              100
  repeat_count:         2
  repeat_mode:          random
  shuffle_seed:         0
  max_inflight:         20
  sleep_after:          0
  expected_ttft_gain:   1.5
  expected_latency_gain: 1.5

docker:
  env:
    - "LMCACHE_CHUNK_SIZE=256"
    - "LMCACHE_LOCAL_CPU=False"
    - "LMCACHE_MAX_LOCAL_DISK_SIZE=5"
    - "LMCACHE_LOCAL_DISK: \"file:///local/end-to-end-tests/local/\""

vllm:
  model: "meta-llama/Llama-3.2-1B-Instruct"
  args:
    - "--load-format"
    - "dummy"
