env:
  DOCKER_BUILDKIT: 1

steps:
  - label: ":rocket: vLLM Integration Tests"
    key: "test"
    timeout_in_minutes: 60
    commands:
      - chmod +x .buildkite/scripts/vllm-integration-tests.sh
      - .buildkite/scripts/vllm-integration-tests.sh --hf-token=$HF_TOKEN --server-wait-timeout=240 --tests=dummy --configs=.buildkite/cases/integration-cases.txt

  - label: ":broom: Clean up"
    depends_on: ["test"]
    allow_dependency_failure: true
    command: |
      export TARGET="$PWD"
      echo "Deleting current workspace $TARGET"
      cd /
      sudo rm -rf "$TARGET"