env:
  DOCKER_BUILDKIT: 1

steps:
  - label: ":rocket: vLLM Integration Tests"
    timeout_in_minutes: 60
    commands:
      - chmod +x .buildkite/scripts/vllm-integration-tests.sh
      - .buildkite/scripts/vllm-integration-tests.sh --hf-token=$HF_TOKEN --server-wait-timeout=240
