
name: Build and Deploy Online Documentation

on:
  # Trigger the workflow on push request,
  # for the dev branch
  push:
    branches:
      - 'dev'
    paths:
      - 'docs/**'
      - 'lmcache/**'
      - 'examples/**'
jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # for setuptools-scm
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Build Sphinx Documentation
        run: |
          sphinx-build docs/source output
        continue-on-error: false

      - name: Add .nojekyll
        run: |
          touch output/.nojekyll

      - name: Upload doc artifacts to GHA
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: doc-artifacts
          path: output/

  deploy-docs:
    name: Deploy docs online
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Fetch doc artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
            name: doc-artifacts
            path: output

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: LM-Cache-Website/lm-cache-website.github.io
          path: target-repo

      - name: Copy Files to Target Repository
        run: |
          cp -r output/* target-repo/

      - name: Commit and Push to Target Repository
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Deploy updated online docs"
            git push https://x-access-token:${{ secrets.LMCACHE_DOC }}@github.com/LM-Cache-Website/lm-cache-website.github.io.git main --force
          else
            echo "No changes to commit."
          fi
