name: Code Quality

on:
  pull_request:
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
        - name: Harden Runner
          uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
          with:
            disable-sudo-and-containers: true
            egress-policy: block
            allowed-endpoints: >
              github.com:443
              pypi.org:443
              files.pythonhosted.org:443

        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            # for setuptools-scm
            fetch-depth: 0

        - name: Setup Python 3.12
          uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with:
            python-version: "3.12"

        - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"

        - name: Run code quality checks - lint, format, spell, & static checks
          uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
          with:
            extra_args: --all-files


